# frozen_string_literal: true

module Sanitizer
  SAFE = {
    '' => true,

    'balance <= channel_balance' => true,
    'pending_open_balance <= channel_balance' => true,
    'sat <= local_balance' => true,
    'msat <= local_balance' => true,
    'sat <= remote_balance' => true,
    'msat <= remote_balance' => true,
    'sat <= unsettled_local_balance' => true,
    'msat <= unsettled_local_balance' => true,
    'sat <= unsettled_remote_balance' => true,
    'msat <= unsettled_remote_balance' => true,
    'sat <= pending_open_local_balance' => true,
    'msat <= pending_open_local_balance' => true,
    'sat <= pending_open_remote_balance' => true,
    'msat <= pending_open_remote_balance' => true,

    'total_balance <= wallet_balance' => true,
    'confirmed_balance <= wallet_balance' => true,
    'unconfirmed_balance <= wallet_balance' => true,
    'locked_balance <= wallet_balance' => true,
    'reserved_balance_anchor_chan <= wallet_balance' => true,
    'confirmed_balance <= default' => true,
    'unconfirmed_balance <= default' => true,

    'is_our_output <= previous_outpoints' => true,
    'is_our_address <= output_details' => true,
    'label <= get_transactions' => true,

    'tx_hash <= get_transactions' => true,
    'amount <= get_transactions' => true,
    'time_stamp <= get_transactions' => true,
    'total_fees <= get_transactions' => true,

    'how <= activities' => true,
    'expires_at <= data' => true,
    'millisatoshis <= received' => true,
    'at <= response' => true,
    'hash' => true,
    '_source <= invoice_decode' => true,
    '_key <= invoice_decode' => true,
    'payable <= invoice_decode' => true,
    'created_at <= invoice_decode' => true,
    'expires_at <= invoice_decode' => true,

    'code <= failure' => true,
    'channel_update <= failure' => true,
    'htlc_msat <= failure' => true,
    'onion_sha_256 <= failure' => true,
    'cltv_expiry <= failure' => true,
    'flags <= failure' => true,
    'failure_source_index <= failure' => true,
    'height <= failure' => true,

    'invoice_decode' => true,

    '_error <= get_node_info' => true,
    'node_id <= hop_hints' => true,
    'chan_id <= hop_hints' => true,
    'fee_base_msat <= hop_hints' => true,
    'fee_proportional_millionths <= hop_hints' => true,
    'cltv_expiry_delta <= hop_hints' => true,

    'code <= invoice_decode' => true,
    '_source <= node_myself' => true,
    '_key <= node_myself' => true,
    'public_key <= node_myself' => true,
    'alias <= node_myself' => true,
    'color <= node_myself' => true,
    'blockchain <= platform' => true,
    'network <= platform' => true,
    'implementation <= lightning' => true,
    'version <= lightning' => true,
    'myself <= node_myself' => true,

    'name <= features' => true,
    'is_known <= features' => true,
    'is_required <= features' => true,
    'set_id <= amp' => true,
    'child_index <= amp' => true,
    'hash <= amp' => true,
    '_key <= data' => true,
    'created_at <= data' => true,
    'settled_at <= data' => true,
    'state <= data' => true,
    'code <= data' => true,
    'payable <= data' => true,
    '_source <= data' => true,
    'known <= data' => true,
    'message <= activities' => true,
    'direction <= activities' => true,
    'at <= activities' => true,
    'kind <= activities' => true,
    'millisatoshis <= amount' => true,
    'id <= channel' => true,
    'at <= payment' => true,

    'hash <= secret' => true,
    'message <= payment' => true,
    '_key <= invoice' => true,
    'created_at <= invoice' => true,
    'settled_at <= invoice' => true,
    'state <= invoice' => true,
    'code <= invoice' => true,
    'payable <= invoice' => true,
    'memo <= description' => true,
    'hash <= description' => true,
    'millisatoshis <= paid' => true,
    'at <= payments' => true,
    'message <= payments' => true,
    '_source <= invoice' => true,
    'known <= invoice' => true,
    'custom_records <= htlcs' => true,
    'payment_hash <= response' => true,
    'value <= response' => true,
    'creation_date <= response' => true,
    'fee <= response' => true,
    'value_sat <= response' => true,
    'value_msat <= response' => true,
    'payment_request <= response' => true,
    'status <= response' => true,
    'fee_sat <= response' => true,
    'fee_msat <= response' => true,
    'creation_time_ns <= response' => true,
    'payment_index <= response' => true,
    'failure_reason <= response' => true,
    'exception' => true,
    'total_time_lock <= payment_route' => true,
    'total_fees <= payment_route' => true,
    'total_amt <= payment_route' => true,
    'custom_records <= hops' => true,
    'total_fees_msat <= payment_route' => true,
    'total_amt_msat <= payment_route' => true,
    'payment_error' => true,
    'payment_route' => true,
    '_error' => true,
    '_code' => true,
    'accept_time <= htlcs' => true,
    'active <= list_channels' => true,
    'active' => true,
    'alias <= describe_graph' => true,
    'alias <= get_info' => true,
    'alias <= node' => true,
    'alias' => true,
    'amount <= pending_htlcs' => true,
    'amt_in <= forwarding_history' => true,
    'amt_in' => true,
    'amt_in_msat <= forwarding_history' => true,
    'amt_in_msat' => true,
    'amt_msat <= htlcs' => true,
    'amt_out <= forwarding_history' => true,
    'amt_out' => true,
    'amt_out_msat <= forwarding_history' => true,
    'amt_out_msat' => true,
    'amt_paid <= list_invoices' => true,
    'amt_paid <= lookup_invoice' => true,
    'amt_paid' => true,
    'amt_paid_msat <= list_invoices' => true,
    'amt_paid_msat <= lookup_invoice' => true,
    'amt_paid_msat' => true,
    'amt_paid_sat <= list_invoices' => true,
    'amt_paid_sat <= lookup_invoice' => true,
    'amt_paid_sat' => true,
    'amt_to_forward <= hops' => true,
    'amt_to_forward_msat <= hops' => true,
    'at <= mine' => true,
    'at' => true,
    'attempt_time_ns <= htlcs' => true,
    'base_fee_msat <= channel_fees' => true,
    'base_fee_msat' => true,
    'capacity <= describe_graph' => true,
    'capacity <= get_chan_info' => true,
    'capacity <= list_channels' => true,
    'capacity' => true,
    'chain <= chains' => true,
    'chan_capacity <= hops' => true,
    'chan_id <= channel_fees' => true,
    'chan_id <= hops' => true,
    'chan_id <= htlcs' => true,
    'chan_id <= list_channels' => true,
    'chan_id' => true,
    'chan_id_in <= forwarding_history' => true,
    'chan_id_in' => true,
    'chan_id_out <= forwarding_history' => true,
    'chan_id_out' => true,
    'chan_point <= describe_graph' => true,
    'chan_point <= get_chan_info' => true,
    'chan_point' => true,
    'channel_id <= describe_graph' => true,
    'channel_id <= get_chan_info' => true,
    'channel_id' => true,
    'channel_point <= channel_fees' => true,
    'channel_point <= list_channels' => true,
    'channel_point' => true,
    'color <= describe_graph' => true,
    'color <= get_info' => true,
    'color <= node' => true,
    'color' => true,
    'creation_date <= list_invoices' => true,
    'creation_date <= list_payments' => true,
    'creation_date <= lookup_invoice' => true,
    'creation_date' => true,
    'creation_time_ns <= list_payments' => true,
    'creation_time_ns' => true,
    'decode_pay_req <= @meta' => true,
    'description <= decode_pay_req' => true,
    'description' => true,
    'description_hash <= decode_pay_req' => true,
    'description_hash <= list_invoices' => true,
    'description_hash <= lookup_invoice' => true,
    'description_hash' => true,
    'disabled <= node1_policy' => true,
    'disabled <= node2_policy' => true,
    'expiry <= decode_pay_req' => true,
    'expiry <= hops' => true,
    'expiry <= list_invoices' => true,
    'expiry <= lookup_invoice' => true,
    'expiry' => true,
    'fee <= forwarding_history' => true,
    'fee <= hops' => true,
    'fee <= list_payments' => true,
    'fee' => true,
    'fee_base_msat <= node1_policy' => true,
    'fee_base_msat <= node2_policy' => true,
    'fee_msat <= forwarding_history' => true,
    'fee_msat <= hops' => true,
    'fee_msat <= list_payments' => true,
    'fee_msat' => true,
    'fee_per_kw <= list_channels' => true,
    'fee_per_kw' => true,
    'fee_per_mil <= channel_fees' => true,
    'fee_per_mil' => true,
    'fee_rate <= channel_fees' => true,
    'fee_rate' => true,
    'fee_rate_milli_msat <= node1_policy' => true,
    'fee_rate_milli_msat <= node2_policy' => true,
    'fee_report <= @meta' => true,
    'fee_sat <= list_payments' => true,
    'fee_sat' => true,
    'get_chan_info <= @meta' => true,
    'get_info <= @meta' => true,
    'get_node_info <= @meta' => true,
    'identity_pubkey <= get_info' => true,
    'identity_pubkey' => true,
    'lifetime <= list_channels' => true,
    'lifetime' => true,
    'list_channels <= @meta' => true,
    'list_payments <= @meta' => true,
    'local_balance <= list_channels' => true,
    'local_balance' => true,
    'lookup_invoice <= @meta' => true,
    'max_htlc_msat <= node1_policy' => true,
    'max_htlc_msat <= node2_policy' => true,
    'max_pending_amt_msat <= local_constraints' => true,
    'max_pending_amt_msat <= remote_constraints' => true,
    'memo <= list_invoices' => true,
    'memo <= lookup_invoice' => true,
    'memo' => true,
    'min_htlc <= node1_policy' => true,
    'min_htlc <= node2_policy' => true,
    'min_htlc_msat <= local_constraints' => true,
    'min_htlc_msat <= remote_constraints' => true,
    'mpp_total_amt_msat <= htlcs' => true,
    'network <= addresses' => true,
    'network <= chains' => true,
    'node1_pub <= describe_graph' => true,
    'node1_pub <= get_chan_info' => true,
    'node1_pub' => true,
    'node2_pub <= describe_graph' => true,
    'node2_pub <= get_chan_info' => true,
    'node2_pub' => true,
    'num_msat <= decode_pay_req' => true,
    'num_msat' => true,
    'num_satoshis <= decode_pay_req' => true,
    'num_satoshis' => true,
    'payment_hash <= decode_pay_req' => true,
    'payment_hash <= list_payments' => true,
    'payment_hash' => true,
    'payment_request <= list_invoices' => true,
    'payment_request <= list_payments' => true,
    'payment_request <= lookup_invoice' => true,
    'payment_request' => true,
    'peer_alias_in <= forwarding_history' => true,
    'peer_alias_in' => true,
    'peer_alias_out <= forwarding_history' => true,
    'peer_alias_out' => true,
    'private' => true,
    'pub_key <= describe_graph' => true,
    'pub_key <= hops' => true,
    'pub_key <= node' => true,
    'pub_key' => true,
    'r_hash <= list_invoices' => true,
    'r_hash <= lookup_invoice' => true,
    'r_hash' => true,
    'remote_balance <= list_channels' => true,
    'remote_balance' => true,
    'remote_pubkey <= list_channels' => true,
    'remote_pubkey' => true,
    'resolve_time <= htlcs' => true,
    'resolve_time_ns <= htlcs' => true,
    'settle_date <= list_invoices' => true,
    'settle_date <= lookup_invoice' => true,
    'settle_date' => true,
    'settled <= list_invoices' => true,
    'settled <= lookup_invoice' => true,
    'settled' => true,
    'state <= htlcs' => true,
    'state <= list_invoices' => true,
    'state <= lookup_invoice' => true,
    'state' => true,
    'status <= htlcs' => true,
    'status <= list_payments' => true,
    'status' => true,
    'time_lock_delta <= node1_policy' => true,
    'time_lock_delta <= node2_policy' => true,
    'timestamp <= decode_pay_req' => true,
    'timestamp <= forwarding_history' => true,
    'timestamp' => true,
    'timestamp_ns <= forwarding_history' => true,
    'timestamp_ns' => true,
    'total_amt <= route' => true,
    'total_amt_msat <= mpp_record' => true,
    'total_amt_msat <= route' => true,
    'total_capacity <= get_node_info' => true,
    'total_capacity' => true,
    'total_fees <= route' => true,
    'total_fees_msat <= route' => true,
    'total_satoshis_received <= list_channels' => true,
    'total_satoshis_received' => true,
    'total_satoshis_sent <= list_channels' => true,
    'total_satoshis_sent' => true,
    'unsettled_balance <= list_channels' => true,
    'unsettled_balance' => true,
    'uptime <= list_channels' => true,
    'uptime' => true,
    'value <= list_invoices' => true,
    'value <= list_payments' => true,
    'value <= lookup_invoice' => true,
    'value' => true,
    'value_msat <= list_invoices' => true,
    'value_msat <= list_payments' => true,
    'value_msat <= lookup_invoice' => true,
    'value_msat' => true,
    'value_sat <= list_payments' => true,
    'value_sat' => true,
    'version <= get_info' => true,
    'version' => true
  }.freeze
end
